name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    outputs:
      requirements: ${{ steps.requirements.outputs.exist }}
      apk: ${{ steps.apk.outputs.packages }}
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: Lint with JQ
        uses: home-assistant/actions/helpers/jq@master

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Check integration files
        id: integrations
        run: |
          for component in components/*; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $component ]]; then
              if [ "${component##*.}" != "json" ];then
                  echo "::error::${component} does not end with '.json'"
                  exit 1
              fi
              manifestlink=$(jq --raw-output ".manifest" "${component}")

              echo "Process: ${component} -> ${manifestlink}"
              manifest=$(curl -sSL -f "${manifestlink}" | jq -e --raw-output .)
              if [[ "$?" != 0 ]]; then
                echo "Unable to read the manifest file at ${manifestlink}"
                echo "The URL might be wrong or is not a raw URL."
                exit 1
              fi

              echo "${manifest}" | jq -e --raw-output '.requirements[0]'
              if [[ "$?" != 0 ]]; then
                echo "The integration in $component, does not seem to have any Python requirements."
                echo "Adding it to this repository has no use, since there are nothing to build for it."
                exit 1
              fi
              
              echo "${manifest}" | jq -e --raw-output '.requirements[]' >> requirements_raw.txt
            fi
          done

      - name: Check if requirements.txt has content
        id: requirements
        run: | 
          if [[ -f ./requirements_raw.txt ]]; then
            sort -u ./requirements_raw.txt > ./requirements.txt
            cat ./requirements.txt
            echo "::set-output name=exist::true"
          fi

      - name: Get constraints
        if: steps.requirements.outputs.exist == 'true'
        run: wget -O constraints.txt https://raw.githubusercontent.com/home-assistant/core/dev/homeassistant/package_constraints.txt

      - name: Upload requirements.txt
        if: steps.requirements.outputs.exist == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: requirements
          path: ./requirements.txt

      - name: Upload constraints.txt
        if: steps.requirements.outputs.exist == 'true'
        uses: actions/upload-artifact@v2
        with:
          name: constraints
          path: ./constraints.txt

      - name: Setup tempio
        uses: home-assistant/tempio@main

      - name: Generate APK list
        id: apk
        run: |
          tempio -conf requirements.json  -template templates/builder.template -out apk.list
          packages=$(cat apk.list)
          echo "::set-output name=packages::${packages}"
        
  integration:
    needs: lint
    runs-on: ubuntu-latest
    name: Validate integration
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container
        run: |
          cp ${HOME}/files.json validate_integrations/files.json
          docker build -t validate -f validate_integrations/Dockerfile .

      - name: Validate integrations
        run: docker run --rm validate

  requirements:
    needs: integration
    runs-on: ubuntu-latest
    name: Validate Python requirements
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container
        run: |
          cp ${HOME}/files.json validate_requirements/files.json
          docker build -t validate -f validate_requirements/Dockerfile .

      - name: Validate requirements
        run: docker run --rm -e CRYPTOGRAPHY_DONT_BUILD_RUST=1 validate

  wheels:
    needs: [lint, requirements]
    if: needs.lint.outputs.requirements == 'true'
    runs-on: ubuntu-latest
    name: Verify that we can build wheels
    strategy:
      matrix:
        arch: ["aarch64", "armhf", "armv7", "amd64", "i386"]
        alpine: ["3.12"]
        python: ["3.8"]

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: Download requirements.txt
        uses: actions/download-artifact@v2
        with:
          name: requirements

      - name: Download constraints.txt
        uses: actions/download-artifact@v2
        with:
          name: constraints

      - name: Build wheels
        uses: home-assistant/wheels@master
        with:
          tag: ${{ matrix.python }}-alpine${{ matrix.alpine }}
          arch: ${{ matrix.arch }}
          wheels-host: ${{ secrets.WHEELS_HOST }}
          apk: ${{ needs.lint.outputs.apk }}
          pip: "Cython;numpy"
          skip-binary: aiohttp
          test: True
          single: True
          constraints: "constraints.txt"
          requirements: "requirements.txt"