name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DEFAULT_PYTHON: 3.8

jobs:
  requirements:
    runs-on: ubuntu-latest
    name: Validate Python requirements
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v2.1.2
        id: python
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: files
        with:
          token: GITHUB_TOKEN
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipdeptree stdlib-list
      - name: Validate requirements
        run: |
          ${{ steps.files.outputs.all }} | scripts/validate_requirements.py
